python train.py --config-name "PASTIS_LIANet" task=PASTIS_T31TFM checkpoint_area="full_tile_modified_PASTIS_T31TFM" val_folds=[4] seed=42 gpu_id=3
python train.py --config-name "PASTIS_LIANet" task=PASTIS_T31TFM checkpoint_area="full_tile_modified_PASTIS_T31TFM" val_folds=[4] seed=111 gpu_id=3
python train.py --config-name "PASTIS_LIANet" task=PASTIS_T31TFM checkpoint_area="full_tile_modified_PASTIS_T31TFM" val_folds=[4] seed=222 gpu_id=3
python train.py --config-name "PASTIS_LIANet" task=PASTIS_T31TFM checkpoint_area="full_tile_modified_PASTIS_T31TFM" val_folds=[4] seed=333 gpu_id=3
python train.py --config-name "PASTIS_LIANet" task=PASTIS_T31TFM checkpoint_area="full_tile_modified_PASTIS_T31TFM" val_folds=[4] seed=444 gpu_id=3
python train.py --config-name "PASTIS_LIANet" task=PASTIS_T31TFM checkpoint_area="full_tile_modified_PASTIS_T31TFM" val_folds=[4] seed=555 gpu_id=3
python train.py --config-name "PASTIS_LIANet" task=PASTIS_T31TFM checkpoint_area="full_tile_modified_PASTIS_T31TFM" val_folds=[4] seed=666 gpu_id=3
python train.py --config-name "PASTIS_LIANet" task=PASTIS_T31TFM checkpoint_area="full_tile_modified_PASTIS_T31TFM" val_folds=[4] seed=777 gpu_id=3
python train.py --config-name "PASTIS_LIANet" task=PASTIS_T31TFM checkpoint_area="full_tile_modified_PASTIS_T31TFM" val_folds=[4] seed=888 gpu_id=3
python train.py --config-name "PASTIS_LIANet" task=PASTIS_T31TFM checkpoint_area="full_tile_modified_PASTIS_T31TFM" val_folds=[4] seed=999 gpu_id=3
#
python train.py --config-name "PASTIS_LIANet" task=PASTIS_T32ULU checkpoint_area="full_tile_modified_PASTIS_T32ULU" val_folds=[4] seed=42 gpu_id=3
python train.py --config-name "PASTIS_LIANet" task=PASTIS_T32ULU checkpoint_area="full_tile_modified_PASTIS_T32ULU" val_folds=[4] seed=111 gpu_id=3
python train.py --config-name "PASTIS_LIANet" task=PASTIS_T32ULU checkpoint_area="full_tile_modified_PASTIS_T32ULU" val_folds=[4] seed=222 gpu_id=3
python train.py --config-name "PASTIS_LIANet" task=PASTIS_T32ULU checkpoint_area="full_tile_modified_PASTIS_T32ULU" val_folds=[4] seed=333 gpu_id=3
python train.py --config-name "PASTIS_LIANet" task=PASTIS_T32ULU checkpoint_area="full_tile_modified_PASTIS_T32ULU" val_folds=[4] seed=444 gpu_id=3
python train.py --config-name "PASTIS_LIANet" task=PASTIS_T32ULU checkpoint_area="full_tile_modified_PASTIS_T32ULU" val_folds=[4] seed=555 gpu_id=3
python train.py --config-name "PASTIS_LIANet" task=PASTIS_T32ULU checkpoint_area="full_tile_modified_PASTIS_T32ULU" val_folds=[4] seed=666 gpu_id=3
python train.py --config-name "PASTIS_LIANet" task=PASTIS_T32ULU checkpoint_area="full_tile_modified_PASTIS_T32ULU" val_folds=[4] seed=777 gpu_id=3
python train.py --config-name "PASTIS_LIANet" task=PASTIS_T32ULU checkpoint_area="full_tile_modified_PASTIS_T32ULU" val_folds=[4] seed=888 gpu_id=3
python train.py --config-name "PASTIS_LIANet" task=PASTIS_T32ULU checkpoint_area="full_tile_modified_PASTIS_T32ULU" val_folds=[4] seed=999 gpu_id=3
#
python train.py --config-name "PASTIS_microUNet" task=PASTIS_T31TFM checkpoint_area="full_tile_modified_PASTIS_T31TFM" val_folds=[4] seed=42 gpu_id=3
python train.py --config-name "PASTIS_microUNet" task=PASTIS_T31TFM checkpoint_area="full_tile_modified_PASTIS_T31TFM" val_folds=[4] seed=111 gpu_id=3
python train.py --config-name "PASTIS_microUNet" task=PASTIS_T31TFM checkpoint_area="full_tile_modified_PASTIS_T31TFM" val_folds=[4] seed=222 gpu_id=3
python train.py --config-name "PASTIS_microUNet" task=PASTIS_T31TFM checkpoint_area="full_tile_modified_PASTIS_T31TFM" val_folds=[4] seed=333 gpu_id=3
python train.py --config-name "PASTIS_microUNet" task=PASTIS_T31TFM checkpoint_area="full_tile_modified_PASTIS_T31TFM" val_folds=[4] seed=444 gpu_id=3
python train.py --config-name "PASTIS_microUNet" task=PASTIS_T31TFM checkpoint_area="full_tile_modified_PASTIS_T31TFM" val_folds=[4] seed=555 gpu_id=3
python train.py --config-name "PASTIS_microUNet" task=PASTIS_T31TFM checkpoint_area="full_tile_modified_PASTIS_T31TFM" val_folds=[4] seed=666 gpu_id=3
python train.py --config-name "PASTIS_microUNet" task=PASTIS_T31TFM checkpoint_area="full_tile_modified_PASTIS_T31TFM" val_folds=[4] seed=777 gpu_id=3
python train.py --config-name "PASTIS_microUNet" task=PASTIS_T31TFM checkpoint_area="full_tile_modified_PASTIS_T31TFM" val_folds=[4] seed=888 gpu_id=3
python train.py --config-name "PASTIS_microUNet" task=PASTIS_T31TFM checkpoint_area="full_tile_modified_PASTIS_T31TFM" val_folds=[4] seed=999 gpu_id=3
#
python train.py --config-name "PASTIS_microUNet" task=PASTIS_T32ULU checkpoint_area="full_tile_modified_PASTIS_T32ULU" val_folds=[4] seed=42 gpu_id=3
python train.py --config-name "PASTIS_microUNet" task=PASTIS_T32ULU checkpoint_area="full_tile_modified_PASTIS_T32ULU" val_folds=[4] seed=111 gpu_id=3
python train.py --config-name "PASTIS_microUNet" task=PASTIS_T32ULU checkpoint_area="full_tile_modified_PASTIS_T32ULU" val_folds=[4] seed=222 gpu_id=3
python train.py --config-name "PASTIS_microUNet" task=PASTIS_T32ULU checkpoint_area="full_tile_modified_PASTIS_T32ULU" val_folds=[4] seed=333 gpu_id=3
python train.py --config-name "PASTIS_microUNet" task=PASTIS_T32ULU checkpoint_area="full_tile_modified_PASTIS_T32ULU" val_folds=[4] seed=444 gpu_id=3
python train.py --config-name "PASTIS_microUNet" task=PASTIS_T32ULU checkpoint_area="full_tile_modified_PASTIS_T32ULU" val_folds=[4] seed=555 gpu_id=3
python train.py --config-name "PASTIS_microUNet" task=PASTIS_T32ULU checkpoint_area="full_tile_modified_PASTIS_T32ULU" val_folds=[4] seed=666 gpu_id=3
python train.py --config-name "PASTIS_microUNet" task=PASTIS_T32ULU checkpoint_area="full_tile_modified_PASTIS_T32ULU" val_folds=[4] seed=777 gpu_id=3
python train.py --config-name "PASTIS_microUNet" task=PASTIS_T32ULU checkpoint_area="full_tile_modified_PASTIS_T32ULU" val_folds=[4] seed=888 gpu_id=3
python train.py --config-name "PASTIS_microUNet" task=PASTIS_T32ULU checkpoint_area="full_tile_modified_PASTIS_T32ULU" val_folds=[4] seed=999 gpu_id=3