python train.py --config-name "BF_clas_UNet" task=BFPBinary_local_T32ULU batchsize=64 learningrate=1e-5 seed=111 gpu_id=0
python train.py --config-name "BF_clas_UNet" task=BFPBinary_local_T32ULU batchsize=64 learningrate=3e-5 seed=111 gpu_id=0
python train.py --config-name "BF_clas_UNet" task=BFPBinary_local_T32ULU batchsize=64 learningrate=1e-4 seed=111 gpu_id=0
python train.py --config-name "BF_clas_UNet" task=BFPBinary_local_T32ULU batchsize=64 learningrate=3e-4 seed=111 gpu_id=0
python train.py --config-name "BF_clas_UNet" task=BFPBinary_local_T32ULU batchsize=64 learningrate=1e-3 seed=111 gpu_id=0
python train.py --config-name "BF_clas_UNet" task=BFPBinary_local_T32ULU batchsize=16 learningrate=1e-5 seed=111 gpu_id=0
python train.py --config-name "BF_clas_UNet" task=BFPBinary_local_T32ULU batchsize=16 learningrate=3e-5 seed=111 gpu_id=0
python train.py --config-name "BF_clas_UNet" task=BFPBinary_local_T32ULU batchsize=16 learningrate=1e-4 seed=111 gpu_id=0
python train.py --config-name "BF_clas_UNet" task=BFPBinary_local_T32ULU batchsize=16 learningrate=3e-4 seed=111 gpu_id=0
python train.py --config-name "BF_clas_UNet" task=BFPBinary_local_T32ULU batchsize=16 learningrate=1e-3 seed=111 gpu_id=0
#
python train.py --config-name "BF_clas_microUNet" task=BFPBinary_local_T32ULU batchsize=64 learningrate=1e-5 seed=111 gpu_id=0
python train.py --config-name "BF_clas_microUNet" task=BFPBinary_local_T32ULU batchsize=64 learningrate=3e-5 seed=111 gpu_id=0
python train.py --config-name "BF_clas_microUNet" task=BFPBinary_local_T32ULU batchsize=64 learningrate=1e-4 seed=111 gpu_id=0
python train.py --config-name "BF_clas_microUNet" task=BFPBinary_local_T32ULU batchsize=64 learningrate=3e-4 seed=111 gpu_id=0
python train.py --config-name "BF_clas_microUNet" task=BFPBinary_local_T32ULU batchsize=64 learningrate=1e-3 seed=111 gpu_id=0
python train.py --config-name "BF_clas_microUNet" task=BFPBinary_local_T32ULU batchsize=16 learningrate=1e-5 seed=111 gpu_id=0
python train.py --config-name "BF_clas_microUNet" task=BFPBinary_local_T32ULU batchsize=16 learningrate=3e-5 seed=111 gpu_id=0
python train.py --config-name "BF_clas_microUNet" task=BFPBinary_local_T32ULU batchsize=16 learningrate=1e-4 seed=111 gpu_id=0
python train.py --config-name "BF_clas_microUNet" task=BFPBinary_local_T32ULU batchsize=16 learningrate=3e-4 seed=111 gpu_id=0
python train.py --config-name "BF_clas_microUNet" task=BFPBinary_local_T32ULU batchsize=16 learningrate=1e-3 seed=111 gpu_id=0