# Hydra config converted from argparse defaults
# Note: choices shown as comments for reference

# This supresses the output folder
# that otherwise is automaticly generated
# by hydra
defaults:
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
hydra:  
  output_subdir: null  
  run:  
    dir: .

seed: 42

task: BFPBinary_joint_T31TFM # choices: [dynamic_world, meta_canopy_height, building_footprints, dominant_leaf_type, building_footprints_binary]
model_type: replace_final_block_4x
train_area_bounds: none
checkpoint_area: none  
val_folds: None


logging_directory: /home/user/results_local/finetuning_results_BFPBinary/ # path to save the finetuning results, e.g. /home/user/results_local/finetuning_results_BFPBinary/

# deep learning related
lossfunction: cross_entropy
batchsize: 8
learningrate: 0.00003
num_workers: 8
epochs: 70
warmup_epochs: 0
gpu_id: 1
validate_every_n_epochs: 2
plot_every_n_epochs: 2
weightedSegmentation: False