# Hydra config converted from argparse defaults
# Note: choices shown as comments for reference

# This supresses the output folder
# that otherwise is automaticly generated
# by hydra
defaults:
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
hydra:  
  output_subdir: null  
  run:  
    dir: .

seed: 42

task: BurnScars
model_type: replace_final_block
checkpoint_area: "full_tile_modified_BurnScars" 
train_area_bounds: none
weightedSegmentation: False
val_folds: None

logging_directory: /home/user/results_local/finetuning_results
labels_path: masks/BurnScars
# deep learning related
lossfunction: cross_entropy
batchsize: 32
learningrate: 0.0001

num_workers: 8
epochs: 50
warmup_epochs: 0
gpu_id: 1
validate_every_n_epochs: 1
plot_every_n_epochs: 1